# Generated by Django 5.1.2 on 2024-10-14 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('persona', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('capacidad_max', models.IntegerField()),
                ('estudiantes', models.ManyToManyField(blank=True, related_name='cursos_estudiante', to='persona.persona')),
                ('profesor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='persona.persona')),
            ],
            options={
                'db_table': 'Curso',
            },
        ),
    ]
